// PDF generation service using jsPDF
// Generates styled A4 PDFs from report data

export async function generateReportPDF(reportData, reportTitle, userName) {
  // Dynamic import to avoid SSR issues
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  const pageW = 210;
  const pageH = 297;
  const margin = 20;
  const contentW = pageW - margin * 2;
  let y = margin;

  const colors = {
    navy: [14, 14, 34],
    gold: [200, 168, 75],
    cream: [250, 248, 242],
    stone: [151, 144, 127],
    white: [255, 255, 255],
  };

  // Helper: add new page if needed
  const checkPage = (needed = 20) => {
    if (y + needed > pageH - margin) {
      doc.addPage();
      y = margin;
      // Page bg
      doc.setFillColor(...colors.navy);
      doc.rect(0, 0, pageW, pageH, 'F');
    }
  };

  // Page 1 background
  doc.setFillColor(...colors.navy);
  doc.rect(0, 0, pageW, pageH, 'F');

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(...colors.cream);
  doc.text(reportTitle || 'Celestia Report', margin, y + 15);
  y += 22;

  // Subtitle
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(...colors.stone);
  doc.text(`Generated for ${userName || 'Explorer'} \u2022 ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, margin, y);
  y += 5;

  // Gold divider
  doc.setDrawColor(...colors.gold);
  doc.setLineWidth(0.5);
  doc.line(margin, y, margin + 40, y);
  y += 10;

  // Summary
  if (reportData?.summary) {
    checkPage(30);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(11);
    doc.setTextColor(...colors.cream);
    const summaryLines = doc.splitTextToSize(reportData.summary, contentW);
    doc.text(summaryLines, margin, y);
    y += summaryLines.length * 5 + 10;
  }

  // Sections
  if (reportData?.sections) {
    for (let i = 0; i < reportData.sections.length; i++) {
      const section = reportData.sections[i];
      checkPage(40);

      // Section number + heading
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.setTextColor(...colors.gold);
      doc.text(`${i + 1}. ${section.heading || ''}`, margin, y);
      y += 8;

      // Body
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(...colors.cream);
      const bodyLines = doc.splitTextToSize(section.body || '', contentW);
      for (const line of bodyLines) {
        checkPage(6);
        doc.text(line, margin, y);
        y += 5;
      }
      y += 4;

      // Remedy
      if (section.remedy) {
        checkPage(15);
        doc.setFillColor(30, 28, 50);
        doc.roundedRect(margin, y - 2, contentW, 0, 3, 3, 'F'); // will size after
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        doc.setTextColor(...colors.gold);
        doc.text('REMEDY', margin + 4, y + 3);
        y += 7;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(...colors.cream);
        const remedyLines = doc.splitTextToSize(section.remedy, contentW - 8);
        doc.text(remedyLines, margin + 4, y);
        y += remedyLines.length * 4 + 6;
      }

      // Affirmation
      if (section.affirmation) {
        checkPage(12);
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(10);
        doc.setTextColor(...colors.gold);
        doc.text(`"${section.affirmation}"`, margin + 10, y);
        y += 8;
      }

      y += 4;
    }
  }

  // Key Insight
  if (reportData?.keyInsight) {
    checkPage(25);
    y += 5;
    doc.setDrawColor(...colors.gold);
    doc.setLineWidth(0.3);
    doc.line(margin, y, margin + contentW, y);
    y += 8;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(...colors.gold);
    doc.text('KEY INSIGHT', margin, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(...colors.cream);
    const insightLines = doc.splitTextToSize(reportData.keyInsight, contentW);
    doc.text(insightLines, margin, y);
    y += insightLines.length * 5 + 8;
  }

  // Footer
  checkPage(15);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...colors.stone);
  doc.text('\u2726 Generated by Celestia \u2022 celestia.app', margin, y);

  // Save
  const filename = `Celestia_${(reportTitle || 'Report').replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}
